server:
  port: 5000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: neo.sophos.dev@gmail.com
    password: mzvqsvuydlxmhlpq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
